-- Run with SQL*Plus as the application schema owner.
-- Initial creation: application tables must not exist.
-- DDL statements commit implicitly in Oracle.

WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

SET SQLBLANKLINES ON

-- Events & Attendees module

CREATE TABLE events (
    event_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR2(150 CHAR) NOT NULL,
    description   VARCHAR2(2000 CHAR),
    event_date    DATE NOT NULL,
    location      VARCHAR2(150 CHAR),
    capacity      NUMBER NOT NULL,

    CONSTRAINT pk_events PRIMARY KEY (event_id),
    CONSTRAINT ck_events_name
        CHECK (REGEXP_LIKE(name, '[^[:space:]]')),
    CONSTRAINT ck_events_capacity
        CHECK (capacity > 0 AND capacity = TRUNC(capacity))
);

CREATE TABLE attendees (
    attendee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR2(100 CHAR) NOT NULL,
    email         VARCHAR2(100 CHAR) NOT NULL,
    phone         VARCHAR2(20 CHAR),

    CONSTRAINT pk_attendees PRIMARY KEY (attendee_id),
    CONSTRAINT uq_attendees_email UNIQUE (email),
    CONSTRAINT ck_attendees_name
        CHECK (REGEXP_LIKE(name, '[^[:space:]]')),
    CONSTRAINT ck_attendees_email
        CHECK (
            REGEXP_LIKE(email, '[^[:space:]]')
            AND email = LOWER(TRIM(email))
        )
);

CREATE TABLE registrations (
    registration_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    event_id        NUMBER NOT NULL,
    attendee_id     NUMBER NOT NULL,
    registered_at   DATE DEFAULT CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) NOT NULL,
    -- Keep the latest cancellation date when the registration is reactivated.
    cancelled_at    DATE,
    status          VARCHAR2(20 CHAR) DEFAULT 'pending' NOT NULL,

    CONSTRAINT pk_registrations PRIMARY KEY (registration_id),
    CONSTRAINT fk_registrations_event
        FOREIGN KEY (event_id) REFERENCES events (event_id),
    CONSTRAINT fk_registrations_attendee
        FOREIGN KEY (attendee_id) REFERENCES attendees (attendee_id),
    CONSTRAINT uq_registration
        UNIQUE (event_id, attendee_id),
    -- Referenced by payments to enforce the same event as the ticket type.
    CONSTRAINT uq_registrations_id_event
        UNIQUE (registration_id, event_id),
    CONSTRAINT ck_registrations_status
        CHECK (status IN ('confirmed', 'cancelled', 'pending')),
    CONSTRAINT ck_registrations_cancelled_at
        CHECK (status <> 'cancelled' OR cancelled_at IS NOT NULL),
    CONSTRAINT ck_registrations_cancel_order
        CHECK (status <> 'cancelled' OR cancelled_at >= registered_at)
);

-- Payments & Reports module

CREATE TABLE ticket_types (
    ticket_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    event_id       NUMBER NOT NULL,
    name           VARCHAR2(50 CHAR) NOT NULL,
    price          NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_ticket_types PRIMARY KEY (ticket_type_id),
    CONSTRAINT fk_ticket_types_event
        FOREIGN KEY (event_id) REFERENCES events (event_id),
    CONSTRAINT uq_ticket_types_id_event
        UNIQUE (ticket_type_id, event_id),
    CONSTRAINT ck_ticket_types_name
        CHECK (REGEXP_LIKE(name, '[^[:space:]]')),
    CONSTRAINT ck_ticket_types_price
        CHECK (price >= 0)
);

CREATE TABLE payments (
    payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    registration_id NUMBER NOT NULL,
    ticket_type_id  NUMBER NOT NULL,
    event_id        NUMBER NOT NULL,
    amount          NUMBER(10,2) NOT NULL,
    paid_at         DATE,
    refunded_at     DATE,
    status          VARCHAR2(20 CHAR) DEFAULT 'pending' NOT NULL,

    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT fk_payments_registration
        FOREIGN KEY (registration_id, event_id)
        REFERENCES registrations (registration_id, event_id),
    CONSTRAINT fk_payments_ticket_type
        FOREIGN KEY (ticket_type_id, event_id)
        REFERENCES ticket_types (ticket_type_id, event_id),
    CONSTRAINT ck_payments_amount
        CHECK (amount >= 0),
    CONSTRAINT ck_payments_status
        CHECK (status IN ('paid', 'pending', 'refunded')),

    -- Refunded payments retain their original payment date.
    CONSTRAINT ck_payments_paid_at
        CHECK (
            (status = 'pending' AND paid_at IS NULL)
            OR
            (status IN ('paid', 'refunded') AND paid_at IS NOT NULL)
        ),
    CONSTRAINT ck_payments_refunded_at
        CHECK (
            (status IN ('pending', 'paid') AND refunded_at IS NULL)
            OR
            (status = 'refunded' AND refunded_at IS NOT NULL)
        ),
    CONSTRAINT ck_payments_refund_order
        CHECK (refunded_at IS NULL OR refunded_at >= paid_at)
);

CREATE TABLE comments (
    comment_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    attendee_id   NUMBER NOT NULL,
    event_id      NUMBER NOT NULL,
    content       VARCHAR2(1000 CHAR) NOT NULL,
    created_at    DATE DEFAULT CAST(SYS_EXTRACT_UTC(SYSTIMESTAMP) AS DATE) NOT NULL,

    CONSTRAINT pk_comments PRIMARY KEY (comment_id),
    CONSTRAINT fk_comments_attendee
        FOREIGN KEY (attendee_id) REFERENCES attendees (attendee_id),
    CONSTRAINT fk_comments_event
        FOREIGN KEY (event_id) REFERENCES events (event_id),
    CONSTRAINT fk_comments_registration
        FOREIGN KEY (event_id, attendee_id)
        REFERENCES registrations (event_id, attendee_id),
    CONSTRAINT ck_comments_content
        CHECK (REGEXP_LIKE(content, '[^[:space:]]'))
);

-- Foreign key indexes.
-- uq_registration already covers lookups starting with event_id.

CREATE INDEX ix_registrations_attendee
    ON registrations (attendee_id);

CREATE INDEX ix_ticket_types_event
    ON ticket_types (event_id);

CREATE INDEX ix_payments_registration
    ON payments (registration_id, event_id);

CREATE INDEX ix_payments_ticket_type
    ON payments (ticket_type_id, event_id);

-- One pending or paid payment per registration; refunds remain as history.
CREATE UNIQUE INDEX uq_payments_active
    ON payments (
        CASE WHEN status <> 'refunded' THEN registration_id END
    );

CREATE INDEX ix_comments_attendee
    ON comments (attendee_id);

CREATE INDEX ix_comments_registration
    ON comments (event_id, attendee_id);

-- Upcoming event queries.

CREATE INDEX ix_events_event_date
    ON events (event_date);

EXIT SUCCESS
